all: normal opt

normal:
	g++ --std=c++14 normal.cpp -o normal.out -lpthread

opt:
	g++ --std=c++14 optimization.cpp -o optimization.out -lpthread

test:
	g++ --std=c++14 test.cpp -o test.out -lpthread -g